### ISSUE TITLE
ERR_TLS_CERT_ALTNAME_INVALID error

### ISSUE THREAD

**Issue by mindthetic** [dimitrinicolas/postcss-inline-media#1]
Hello,

I'm getting the following error when I try to install using

```
npm install postcss-inline-media
```
results in the following error

```
npm ERR! code ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! errno ERR_TLS_CERT_ALTNAME_INVALID
npm ERR! request to https://registry.npmjs.org/postcss-inline-media/-/postcss-inline-media-1.3.0.tgz failed, reason: Hostname/IP does not match certificate's altnames: Host: registry.npmjs.org. is not in the cert's altnames: DNS:a.sni.fastly.net, DNS:a.sni.global-ssl.fastly.net
```

This sounds like an issue with the npmjs website but I don't know if I'm reading that right. What are your thoughts?

**Comment by dimitrinicolas** [comment]
Hi!

I've never met this error, by reading it I would definitly say that it's an NPM error, but not sure. I'll suggest you to look for a similar issue without the "postcss-inline-media" specificity.

I am off this week-end, so I can't help you more for thus moment.

Keep me informed!

**Comment by mindthetic** [comment]
Hi Dimitri,

I've never seen this error before but I think you're right. I found there is an incident on npmjs.com with a DNS issue.

https://status.npmjs.org/incidents/v22ffls5cd6h

**Comment by mindthetic** [comment]
If you follow the advice around adding the IP address to your host file and then restart your computer it seems to be a work around for the issue.

Sorry to have bothered you. Thanks for listening.

**Comment by dimitrinicolas** [comment]
Oh well spotted, have a nice week-end and good luck with NPM!
