### ISSUE TITLE
A PostCSS plugin did not pass the `from` option to `postcss.parse`. This may cause imported assets to be incorrectly transformed. If you've recently added a PostCSS plugin that raised this warning, please contact the package author to fix the issue.

### ISSUE THREAD

**Issue by stephanedemotte** [dimitrinicolas/postcss-inline-media#13]
I've got this warning with vite.js, i'm trying to fix it, but i don't get it :)

```
A PostCSS plugin did not pass the `from` option to `postcss.parse`. This may cause imported assets to be incorrectly transformed. If you've recently added a PostCSS plugin that raised this warning, please contact the package author to fix the issue.
``` 

When i comment line 47 -> 50, 60, 97 this message disappear, but the plugin don't work anymore ;)

If you can have a look, it could b cool to remove this warning, the plugin still work but it's annoying :)

Thank for this !

**Comment by dimitrinicolas** [comment]
Hi @stephanedemotte,
Thank you for your message,

For information, I personally no longer use this plugin.

But  I remember trying in vain to get rid of this warning when initially building the plugin. Unfortunately, it didn't seem technically possible to make it possible without the warning.

I hope you don't have a problem with that,
Dimitri
