### ISSUE TITLE
Add setting for less than, or less than or equal to for values

### ISSUE THREAD

**Issue by alexanderscottgraham** [dimitrinicolas/postcss-inline-media#3]
Having `color: blue @768 red` change on **>=768px**, instead of **>768px**, would be fantastic. Currently trying to find where to edit this in the index but cannot find it.

**Comment by dimitrinicolas** [comment]
Hi! I've juste published a new version of this plugin, I added a `shorthandValueAddition` option where you can put a relative number to add to a shorthand media query value.

For example:

```js
// With this plugin configuration:
require('postcss-inline-media')({
  shorthandValueAddition: -1,
})
```

```pcss
a {
  color: blue @768 red;
}
// Will output:
a {
  color: blue;
}
@media (max-width: 767px) {
  a {
    color: red;
  }
}
```

**Comment by alexanderscottgraham** [comment]
Thank you so much! This is exactly what I needed. Fast response too.
